Update BA reference table
singularity-energy/open-grid-emissions pull request #394
Opened 2024-11-19 00:56 UTC by rouille

### Purpose
Update BA reference table. Fix the notebook used to manually update the BA reference table.

### What the code is doing
I did not have the  "Allowable Entries for Balancing Authorities and Hubs" file from FERC so I could not run the notebook. After downloading the file, I preprocessed it and refactor the notebokk to be able to updated the existing BA reference table. Existing and updated file are identical as the FERC data have not changed since last release.

### Testing
Ran the notebook and then:
```
>>> import pandas as pd
>>> ba_reference = (
...     pd.read_csv("../../src/oge/reference_tables/ba_reference.csv")
...     .sort_values(by=["ba_code"])
... )
>>> ba_reference
    ba_code                                         ba_name      ba_category  ... retirement_date_ferc      source ba_number
0      AEBN                                AESC, LLC - AEBN              NaN  ...                  NaN        FERC         1
1       AEC                   PowerSouth Energy Cooperative              NaN  ...                  NaN  EIA & FERC         2
2      AECI           Associated Electric Cooperative, Inc.              NaN  ...                  NaN  EIA & FERC         3
3      AEGL                             AESC, LLC - Gleason              NaN  ...                  NaN        FERC         4
4      AELC                      AESC, LLC - Lincoln Center              NaN  ...                  NaN        FERC         5
..      ...                                             ...              ...  ...                  ...         ...       ...
206     WPS            Wisconsin Public Service Corporation              NaN  ...                  NaN        FERC       207
207      WR             Western Resources dba Westar Energy              NaN  ...                  NaN        FERC       208
208     WWA                       NaturEner Wind Watch, LLC  generation_only  ...                  NaN  EIA & FERC       209
209     YAD  Alcoa Power Generating, Inc. - Yadkin Division  generation_only  ...                  NaN  EIA & FERC       210
239     NaN                          No Balancing Authority    miscellaneous  ...                  NaN         NaN       999

[240 rows x 13 columns]
>>> ba_reference_updated = pd.read_csv(
...     "../../src/oge/reference_tables/ba_reference.csv"
... ).sort_values(by=["ba_code"])[ba_reference.columns]
ba_reference_updated>>> ba_reference_updated
    ba_code                                         ba_name      ba_category  ... retirement_date_ferc      source ba_number
0      AEBN                                AESC, LLC - AEBN              NaN  ...                  NaN        FERC         1
1       AEC                   PowerSouth Energy Cooperative              NaN  ...                  NaN  EIA & FERC         2
2      AECI           Associated Electric Cooperative, Inc.              NaN  ...                  NaN  EIA & FERC         3
3      AEGL                             AESC, LLC - Gleason              NaN  ...                  NaN        FERC         4
4      AELC                      AESC, LLC - Lincoln Center              NaN  ...                  NaN        FERC         5
..      ...                                             ...              ...  ...                  ...         ...       ...
206     WPS            Wisconsin Public Service Corporation              NaN  ...                  NaN        FERC       207
207      WR             Western Resources dba Westar Energy              NaN  ...                  NaN        FERC       208
208     WWA                       NaturEner Wind Watch, LLC  generation_only  ...                  NaN  EIA & FERC       209
209     YAD  Alcoa Power Generating, Inc. - Yadkin Division  generation_only  ...                  NaN  EIA & FERC       210
239     NaN                          No Balancing Authority    miscellaneous  ...                  NaN         NaN       999

[240 rows x 13 columns]
>>> ba_reference.equals(ba_reference_updated)
True 
```

### Where to look
* In the **ba_reference.csv** file, several retirement dates have been updated using the EIA list of Balancing Authorities
* In the notebook, add documentation and code to guide the user to process the FERC data before merging it to the existing BA reference table. 

### Usage Example/Visuals
N/A

### Review estimate
10min

### Future work
Clear outputs of notebook after review

### Checklist
- [x] Update the documentation to reflect changes made in this PR
- [x] Format all updated python files using `ruff`
- [ ] Clear outputs from all notebooks modified
- [x] Add docstrings and type hints to any new functions created

2024-11-19 17:53 UTC, grgmiller reviewed
See comments, we may want to make some changes

2024-11-19 18:56 UTC, rouille commented on src/oge/reference_tables/ba_reference.csv
> +AESO,Alberta Electric System Operator,rto,Canada/Mountain,Canada/Mountain,No,1/1/2004,2/2/2022,,,,EIA & FERC,7
I noticed the dates were identical for BAs outside the US. I will remove the retirement dates for these

2024-11-19 19:03 UTC, rouille commented on src/oge/reference_tables/eGRID_crosswalk_of_EIA_ID_to_EPA_ID.csv
> -54995,10474,10474
Added back

2024-11-19 19:03 UTC, rouille commented on src/oge/reference_tables/ba_reference.csv
> +AESO,Alberta Electric System Operator,rto,Canada/Mountain,Canada/Mountain,No,1/1/2004,2/2/2022,,,,EIA & FERC,7
Done

2024-11-23 20:33 UTC, grgmiller requested changes
One small change requested for one of the new energy sources, but otherwise this looks good.

Also, please clear notebook outputs before merging.

2024-11-25 17:51 UTC, rouille commented on src/oge/reference_tables/steam_units_to_remove.csv
Do you want to discard the changes I introduces or it does not matter since we don't use this input antway.

2024-11-25 18:19 UTC, rouille commented on src/oge/reference_tables/energy_source_groups.csv
> +BU,Butane Gas, natural_gas,natural_gas,gas,natural_gas
Done

2024-11-26 18:26 UTC, grgmiller commented on src/oge/reference_tables/steam_units_to_remove.csv
I think we can keep them.

2024-11-26 18:27 UTC, grgmiller approved these changes
Thank you, looks good!

2024-11-26 18:33 UTC, merged